predicates_mapping = {
    "P181002": {
        "label": "RE task",
        "cardinality": "one to one",
        "description": "What requirements engineering task is your study addressing?",
        "question_mapping": "I.1",
        "resource_mapping_key": "RE task",
        "comma_separated": False,
    },
    "P181003": {
        "label": "NLP task",
        "cardinality": "one to one",
        "description": "What natural language processing task is your study tackling?",
        "subtemplate_id": "R1544138",
        "class_id": "C121004",
        "subtemplate_properties": {
            "P181004": {
                "label": "NLP task type",
                "cardinality": "one to many",
                "description": "What type of natural language processing task is your study tackling?",
                "question_mapping": "II.1",
                "resource_mapping_key": "NLP task type",
                "comma_separated": False,
            },
            "P181005": {
                "label": "NLP task input",
                "cardinality": "one to many",
                "description": "What is the input of your natural language processing task?",
                "question_mapping": "III.1",
                "resource_mapping_key": "NLP task input",
                "comma_separated": False,
            },
            "P181007": {
                "label": "NLP task output type",
                "cardinality": "one to many",
                "description": "What is the output of your natural language processing task?",
                "question_mapping": [
                    "III.2",
                    "III.4",
                    "III.6",
                    "III.8",
                    "III.9",
                ],
                "resource_mapping_key": "NLP task output type",
                "comma_separated": False,
            },
            "P181008": {
                "label": "NLP task output classification label",
                "cardinality": "one to one",
                "description": "What are the labels that can be assigned?",
                "question_mapping": "III.3",
                "resource_mapping_key": "NLP task output classification label",
                "comma_separated": False,
            },
            "P181009": {
                "label": "NLP task output extracted element",
                "cardinality": "one to one",
                "description": "What is the type of the extracted elements?",
                "question_mapping": "III.5",
                "resource_mapping_key": "NLP task output extracted element",
                "comma_separated": False,
            },
            "P181010": {
                "label": "NLP task output translation mapping cardinality",
                "cardinality": "one to one",
                "description": "What is the translation mapping cardinality between initial input and final output?",
                "question_mapping": "III.7",
                "resource_mapping_key": "NLP task output translation mapping cardinality",
                "comma_separated": False,
            },
        },
    },
    "P181011": {
        "label": "NLP dataset",
        "cardinality": "one to one",
        "description": "What natural language processing dataset is your study using?",
        "subtemplate_id": "R1544216",
        "class_id": "C121010",
        "subtemplate_properties": {
            "P181015": {
                "label": "NLP data item",
                "cardinality": "one to one",
                "description": "How many data items do you process?",
                "question_mapping": "IV.1",
                "resource_mapping_key": "NLP data item",
                "comma_separated": False,
            },
            "P181016": {
                "label": "NLP data production time",
                "cardinality": "one to one",
                "description": "In which year or interval of year were the data produced?",
                "question_mapping": "IV.2",
                "resource_mapping_key": "NLP data prodcution time",
                "comma_separated": False,
            },
            "P181017": {
                "label": "NLP data source",
                "cardinality": "one to one",
                "description": "What is the source of the data?",
                "subtemplate_id": "R1544223",
                "class_id": "C121011",
                "subtemplate_properties": {
                    "P181018": {
                        "label": "NLP data source type",
                        "cardinality": "one to one",
                        "description": "What is the source type of the data?",
                        "question_mapping": "IV.3",
                        "resource_mapping_key": "NLP data source type",
                        "comma_separated": False,
                    },
                    "P181019": {
                        "label": "Number of data sources",
                        "cardinality": "one to one",
                        "description": "From how many different sources your data comes from?",
                        "question_mapping": "IV.9",
                        "resource_mapping_key": "Number of data sources",
                        "comma_separated": False,
                    },
                    "P181020": {
                        "label": "NLP data source domain",
                        "cardinality": "one to many",
                        "description": "Please list which domains your data belongs to?",
                        "question_mapping": "IV.8",
                        "resource_mapping_key": "NLP data source domain",
                        "comma_separated": True,
                    },
                },
            },
            "P181021": {
                "label": "NLP data abstraction level",
                "cardinality": "one to many",
                "description": "What is the level of abstraction of the data?",
                "question_mapping": "IV.4",
                "resource_mapping_key": "NLP data abstraction level",
                "comma_separated": False,
            },
            "P181022": {
                "label": "NLP data type",
                "cardinality": "one to one",
                "description": "What is the type of the data?",
                "subtemplate_id": "R1544245",
                "class_id": "C121015",
                "subtemplate_properties": {
                    "P181023": {
                        "label": "NLP data format",
                        "cardinality": "one to one",
                        "description": "What is the format of the data?",
                        "question_mapping": "IV.5",
                        "resource_mapping_key": "NLP data format",
                        "comma_separated": False,
                    },
                    "P181024": {
                        "label": "Rigor of data format",
                        "cardinality": "one to many",
                        "description": "How rigorous is the data format?",
                        "question_mapping": "IV.6",
                        "resource_mapping_key": "Rigor of data format",
                        "comma_separated": False,
                    },
                    "P181025": {
                        "label": "Natural language",
                        "cardinality": "one to one",
                        "description": "What is the natural language of the data?",
                        "question_mapping": "IV.7",
                        "resource_mapping_key": "Natural language",
                        "comma_separated": False,
                    },
                },
            },
            "license": {
                "label": "License",
                "cardinality": "one to one",
                "description": "What license information applies?",
                "subtemplate_id": "R1544265",
                "class_id": "C121018",
                "subtemplate_properties": {
                    "P181026": {
                        "label": "Public availability",
                        "cardinality": "one to one",
                        "description": "Is the dataset publicly available?",
                        "question_mapping": "IV.10",
                        "resource_mapping_key": "Public availability",
                        "comma_separated": False,
                    },
                    "P181027": {
                        "label": "License type",
                        "cardinality": "one to one",
                        "description": "What is the type of the license?",
                        "question_mapping": "IV.11",
                        "resource_mapping_key": "License type",
                        "comma_separated": False,
                    },
                },
            },
            "P181028": {
                "label": "Dataset location",
                "cardinality": "one to one",
                "description": "Where is the dataset stored?",
                "subtemplate_id": "R1544278",
                "class_id": "C121022",
                "subtemplate_properties": {
                    "P181030": {
                        "label": "Location type",
                        "cardinality": "one to many",
                        "description": "Where is the dataset stored?",
                        "question_mapping": "IV.12",
                        "resource_mapping_key": "Location type",
                        "comma_separated": False,
                    },
                    "P1003": {
                        "label": "URL",
                        "cardinality": "one to one",
                        "description": "Provide a URL to the dataset",
                        "question_mapping": "IV.13",
                        "resource_mapping_key": "url",
                        "comma_separated": False,
                    },
                },
            },
        },
    },
    "P181031": {
        "label": "Annotation Process",
        "cardinality": "one to one",
        "description": "What annotation process did you use for your dataset?",
        "subtemplate_id": "R1544287",
        "class_id": "C121025",
        "subtemplate_properties": {
            "P181032": {
                "label": "Annotator",
                "cardinality": "one to one",
                "description": "Who are the annotators of your dataset?",
                "subtemplate_id": "R1544290",
                "class_id": "C121026",
                "subtemplate_properties": {
                    "P59120": {
                        "label": "Number of annotators",
                        "cardinality": "one to one",
                        "description": "How many annotators have been involved?",
                        "question_mapping": "V.1",
                        "resource_mapping_key": "Number of annotators",
                        "comma_separated": False,
                    },
                    "P181033": {
                        "label": "Annotator assignment",
                        "cardinality": "one to many",
                        "description": "How are the entries annotated?",
                        "question_mapping": "V.2",
                        "resource_mapping_key": "Annotator assignment",
                        "comma_separated": False,
                    },
                    "P181034": {
                        "label": "Level of application domain experience",
                        "cardinality": "one to many",
                        "description": "What is the level of application domain experience?",
                        "question_mapping": "V.3",
                        "resource_mapping_key": "Level of application domain experience",
                        "comma_separated": False,
                    },
                    "P181035": {
                        "label": "Annotator identity",
                        "cardinality": "one to many",
                        "description": "Who are the annotators?",
                        "question_mapping": "V.4",
                        "resource_mapping_key": "Annotator identity",
                        "comma_separated": False,
                    },
                },
            },
            "P181036": {
                "label": "Annotation scheme",
                "cardinality": "one to many",
                "description": "What is the annotation scheme used?",
                "subtemplate_id": "R1544307",
                "class_id": "C121030",
                "subtemplate_properties": {
                    "P181037": {
                        "label": "Scheme establishment",
                        "cardinality": "one to many",
                        "description": "How was the annotation scheme established?",
                        "question_mapping": "V.5",
                        "resource_mapping_key": "Scheme establishement",
                        "comma_separated": False,
                    },
                    "P181038": {
                        "label": "Guideline availability",
                        "cardinality": "one to many",
                        "description": "Did you make the written guidelines public?",
                        "question_mapping": "V.6",
                        "resource_mapping_key": "Guideline availability",
                        "comma_separated": False,
                    },
                },
            },
            "P181039": {
                "label": "Shared material",
                "cardinality": "one to one",
                "description": "Did you share other information to support annotators?",
                "question_mapping": "V.7",
                "resource_mapping_key": "Shared material",
                "comma_separated": False,
            },
            "P181040": {
                "label": "Fatigue mitigation technique",
                "cardinality": "one to one",
                "description": "Did you employ techniques to mitigate fatigue effects?",
                "question_mapping": "V.8",
                "resource_mapping_key": "Fatigue mitigation technique",
                "comma_separated": False,
            },
            "P181041": {
                "label": "Annotator agreement",
                "cardinality": "one to one",
                "description": "What annotator agreement did you apply?",
                "subtemplate_id": "R1544326",
                "class_id": "C121035",
                "subtemplate_properties": {
                    "P181042": {
                        "label": "Intercoder reliability metric",
                        "cardinality": "one to many",
                        "description": "What are the metrics used to measure intercoder reliability?",
                        "question_mapping": "V.9",
                        "resource_mapping_key": "Intercoder reliability metric",
                        "comma_separated": False,
                    },
                    "P181044": {
                        "label": "Conflict resolution",
                        "cardinality": "one to many",
                        "description": "How were conflicts resolved?",
                        "question_mapping": "V.10",
                        "resource_mapping_key": "Conflict resolution",
                        "comma_separated": False,
                    },
                    "P181045": {
                        "label": "Measured agreement",
                        "cardinality": "one to one",
                        "description": "What is the measured agreement?",
                        "question_mapping": "V.11",
                        "resource_mapping_key": "Measured agreement",
                        "comma_separated": False,
                    },
                },
            },
        },
    },
    "P181046": {
        "label": "Implemented approach",
        "cardinality": "one to one",
        "description": "What approach did you implement?",
        "subtemplate_id": "R1544363",
        "class_id": "C121038",
        "subtemplate_properties": {
            "P5043": {
                "label": "Approach type",
                "cardinality": "one to many",
                "description": "What is the type of proposed solution?",
                "question_mapping": "VI.1",
                "resource_mapping_key": "Approach type",
                "comma_separated": False,
            },
            "P58069": {
                "label": "Algorithm used",
                "cardinality": "one to many",
                "description": "What algorithms are used in the tool?",
                "question_mapping": "VI.2",
                "resource_mapping_key": "Algorithm used",
                "comma_separated": True,
            },
            "P181047": {
                "label": "Running requirements",
                "cardinality": "one to many",
                "description": "What needs to be done for running the tool?",
                "question_mapping": "VI.4",
                "resource_mapping_key": "Running requirements",
                "comma_separated": False,
            },
            "P41835": {
                "label": "Documentation",
                "cardinality": "one to many",
                "description": "What type of documentation has been provided?",
                "question_mapping": "VI.5",
                "resource_mapping_key": "Documentation",
                "comma_separated": False,
            },
            "P181048": {
                "label": "Dependency",
                "cardinality": "one to many",
                "description": "What type of dependencies does the tool have?",
                "question_mapping": "VI.6",
                "resource_mapping_key": "Dependency",
                "comma_separated": False,
            },
            "P181049": {
                "label": "License type",
                "cardinality": "one to one",
                "description": "What license has been used?",
                "question_mapping": "VI.8",
                "resource_mapping_key": "license type",
                "comma_separated": False,
            },
            "release": {
                "label": "Release",
                "cardinality": "one to one",
                "description": "How was the tool released?",
                "subtemplate_id": "R1544401",
                "class_id": "C121044",
                "subtemplate_properties": {
                    "P181051": {
                        "label": "Release format",
                        "cardinality": "one to many",
                        "description": "What has been released?",
                        "question_mapping": "VI.3",
                        "resource_mapping_key": "Release format",
                        "comma_separated": False,
                    },
                    "P181029": {
                        "label": "Location type",
                        "cardinality": "one to many",
                        "description": "How is the tool released?",
                        "question_mapping": "VI.7",
                        "resource_mapping_key": "Location type",
                        "comma_separated": False,
                    },
                    "P1003": {
                        "label": "URL",
                        "cardinality": "one to one",
                        "description": "Where is the tool released?",
                        "question_mapping": "VI.9",
                        "resource_mapping_key": "url",
                        "comma_separated": False,
                    },
                },
            },
        },
    },
    "HAS_EVALUATION": {
        "label": "Evaluation",
        "cardinality": "one to one",
        "description": "What evaluation did you apply?",
        "subtemplate_id": "R1544421",
        "class_id": "C121047",
        "subtemplate_properties": {
            "P110006": {
                "label": "Evaluation metric",
                "cardinality": "one to many",
                "description": "What metrics are used to evaluate the approach?",
                "question_mapping": "VII.1",
                "resource_mapping_key": "Evaluation metric",
                "comma_separated": True,
            },
            "P181050": {
                "label": "Validation procedure",
                "cardinality": "one to many",
                "description": "What is the validation procedure?",
                "question_mapping": "VII.2",
                "resource_mapping_key": "Validation procedure",
                "comma_separated": False,
            },
            "P181051": {
                "label": "Baseline comparison",
                "cardinality": "one to one",
                "description": "What is the baseline comparison?",
                "subtemplate_id": "R1544450",
                "class_id": "C121050",
                "subtemplate_properties": {
                    "P181052": {
                        "label": "Baseline comparison type",
                        "cardinality": "one to many",
                        "description": "What baseline do you compare against?",
                        "question_mapping": "VII.3",
                        "resource_mapping_key": "Baseline comparsion type",
                        "comma_separated": False,
                    },
                    "P181053": {
                        "label": "Baseline comparison details",
                        "cardinality": "one to one",
                        "description": "Please provide more details about the baseline?",
                        "question_mapping": "VII.4",
                        "resource_mapping_key": "Baseline comparison details",
                        "comma_separated": False,
                    },
                },
            },
        },
    },
}

resource_mappings = {
    "RE task": {
        "Requirements retrieval": "R1544135",
        "Requirements tracing": "R1544133",
        "Information extraction from legal documents": "R1544136",
        "Requirements defect detection": "R1544134",
        "Requirements classification": "R1544130",
        "Model generation": "R1544132",
        "App review analysis": "R1544129",
        "Dependency and relation extraction": "R1544131",
        "Test generation": "R1544128",
        "Information extraction from requirements": "R1544127",
    },
    "NLP task type": {
        "Information extraction": "R1544150",
        "Information retrieval": "R1544149",
        "Classification": "R1544148",
        "Translation": "R1544147",
    },
    "NLP task input": {
        "Words": "R1544156",
        "Structured/tabular text": "R1544155",
        "Phrases": "R1544154",
        "Document": "R1544153",
        "Paragraphs": "R1544151",
        "Sentences": "R1544152",
    },
    "NLP task output type": {
        "Text": "R1544175",
        "Binary-multi label": "R1544174",
        "Multi class-single label": "R1544171",
        "Multi class-multi label": "R1544169",
        "Phrases": "R1544167",
        "Sentences": "R1544173",
        "Words": "R1544170",
        "Table": "R1544172",
        "Graphical diagram": "R1544168",
        "Document": "R1544166",
        "Binary-single label": "R1544161",
        "Executable model": "R1544165",
        "Paragraphs": "R1544164",
        "Test cases": "R1544163",
    },
    "NLP task output translation mapping cardinality": {
        "Not reported": "R1544465",
        "Many to Many": "R1544187",
        "Many to 1": "R1544186",
        "1 to many": "R1544185",
        "1 to 1": "R1544184",
    },
    "NLP data source type": {
        "Textbook examples or cases": "R1544232",
        "Student projects": "R1544231",
        "Industrial project, publicly available data": "R1544230",
        "User generated content": "R1544229",
        "Toy Requirements": "R1544227",
        "Industrial project, proprietary data": "R1544228",
        "Legal/regulatory documents": "R1544226",
        "Community-based open source projects": "R1544225",
    },
    "NLP data source domain": {
        "Not reported": "R1544550",
    },
    "NLP data abstraction level": {
        "Module-level": "R1544243",
        "Code-level": "R1544242",
        "System-level": "R1544241",
        "Business-level": "R1544240",
        "Normative-level": "R1544239",
        "User-level": "R1544238",
    },
    "NLP data format": {
        "Legal text": "R1544255",
        "Messages in user forums": "R1544254",
        "Social media posts": "R1544256",
        "Bug/defect reports": "R1544253",
        "User reviews": "R1544252",
        "Use cases": "R1544251",
        "Graphical diagrams": "R1544247",
        "User stories": "R1544248",
        "Scenarios": "R1544250",
        '"Shall" requirements': "R1544249",
    },
    "Rigor of data format": {
        "Semantically-augmented natural language": "R1544261",
        "Restricted grammar based controlled natural language": "R1544260",
        "Template-based controlled natural language": "R1544259",
        "Unconstrained natural language": "R1544258",
    },
    "Public availability": {
        "Upon Request": "R1544270",
        "Partially": "R1544269",
        "No": "R1544268",
        "Fully": "R1544267",
    },
    "License type": {
        "Not reported": "R1544495",
        "No license": "R1544274",
        "License: Reuse for any purposes": "R1544276",
        "License: Modification only for non-commercial purposes": "R1544275",
        "License: Modification for any purposes": "R1544273",
        "License: Reuse only for non-commercial purposes": "R1544272",
    },
    "Location type": {
        "Not reported": "R1544497",
        "In a persistent platform with DOI": "R1544282",
        "In a repository": "R1544281",
        "On a private/corporate website": "R1544280",
    },
    "Annotator assignment": {
        "One annotator per entry (quality control, possibly on a sample)": "R1544296",
        "One annotator per entry (no quality control)": "R1544295",
        "Partly multiple annotators per entry, partly one annotator per entry": "R1544294",
        "Multiple annotators per entry": "R1544293",
    },
    "Level of application domain experience": {
        "None or unknown": "R1544298",
        "Domain expert": "R1544299",
        "Informed outsider": "R1544300",
    },
    "Annotator identity": {
        "The designers of the technique/tool": "R1544302",
        "People who have direct contact with the designers": "R1544304",
        "Independent annotators": "R1544303",
    },
    "Scheme establishement": {
        "Written guidelines with label definitions": "R1544312",
        "Oral agreement among the annotators": "R1544311",
        "Only via class labels": "R1544309",
        "Written guidelines with definitions and examples": "R1544310",
    },
    "Guideline availability": {
        "Not reported": "R1544508",
        "Yes, via a persistent URL": "R1544317",
        "Yes, via a non-persistent URL": "R1544316",
        "No, but are made available upon request": "R1544315",
        "No": "R1544314",
    },
    "Shared material": {
        "Entire document": "R1544321",
        "Surrounding context": "R1544320",
        "No": "R1544319",
    },
    "Fatigue mitigation technique": {
        "No": "R1544324",
        "Yes": "R1544323",
    },
    "Intercoder reliability metric": {
        "Not reported": "R1544513",
        "Krippendorf's Alpha": "R1544330",
        "Fleiss K": "R1544329",
        "Cohen's K": "R1544328",
    },
    "Conflict resolution": {
        "Disagreements were disregarded": "R1544338",
        "Not resolved": "R1544335",
        "Majority voting": "R1544336",
        "Resolution by independent expert (not an annotator)": "R1544337",
        "Resolution by authors": "R1544334",
        "Discussion among annotators": "R1544333",
    },
    "Approach type": {
        "Unsupervised DL": "R1544369",
        "Supervised ML": "R1544368",
        "Rule-based": "R1544366",
        "Unsupervised ML": "R1544367",
        "Supervised DL": "R1544365",
    },
    "Algorithm used": {
        "Not reported": "R1544560",
    },
    "Running requirements": {
        "Not reported": "R1544524",
        "Virtual machine / Docker container": "R1544383",
        "Reproduce the tool from the explanation in the paper": "R1544382",
        "Import and integrate into your own code": "R1544381",
        "Compile and run": "R1544380",
        "No installation is needed": "R1544379",
    },
    "Documentation": {
        "Not reported": "R1544527",
        "Wiki or dedicated website": "R1544391",
        "README file": "R1544390",
        "An academic paper": "R1544386",
        "No documentation": "R1544389",
        "Tutorial": "R1544388",
        "Ready-to-use examples": "R1544387",
        "Pseudocode /illustration in the paper": "R1544385",
    },
    "Dependency": {
        "Not reported": "R1544528",
        "Specific OS": "R1544395",
        "Specific hardware": "R1544398",
        "Proprietary libraries/software": "R1544396",
        "External knowledge bases": "R1544397",
        "Open source libraries / software": "R1544394",
        "None": "R1544393",
    },
    "Release format": {
        "Library/API": "R1544411",
        "Pre-trained model": "R1544409",
        "Source code": "R1544410",
        "Executable notebook": "R1544407",
        "Service on the web": "R1544408",
        "Tool - standalone": "R1544405",
        "No tool has been released": "R1544406",
    },
    "Evaluation metric": {
        "MAP": "R1544443",
        "F-Score": "R1544442",
        "NIST-METEOR-ROUGE - BLEU": "R1544441",
        "Accuracy": "R1544440",
        "LAG": "R1544439",
        "AUC": "R1544438",
        "WER (word error rate)": "R1544437",
        "Precision/Recall": "R1544436",
    },
    "Validation procedure": {
        "Cross-project validation": "R1544447",
        "Cross-validation": "R1544448",
        "Train-test split": "R1544445",
        "Entire dataset": "R1544446",
    },
    "Baseline comparsion type": {
        "Theoretical/conceptual": "R1544457",
        "None": "R1544454",
        "Existing tool or algorithm": "R1544455",
        "Reconstructed tool from other research": "R1544456",
        "Automated, but self-defined": "R1544453",
        "Human baseline": "R1544452",
    },
}


class_mappings = {
    "RE task": "C121003",
    "NLP task type": "C121005",
    "NLP task input": "C121006",
    "NLP task output type": "C121008",
    "NLP task output translation mapping cardinality": "C121009",
    "NLP data source type": "C121012",
    "NLP data source domain": "C121053",
    "NLP data abstraction level": "C121013",
    "NLP data format": "C121016",
    "Rigor of data format": "C121017",
    "Public availability": "C121019",
    "License type": "C121020",
    "Location type": "C121024",
    "Annotator assignment": "C121027",
    "Level of application domain experience": "C121028",
    "Annotator identity": "C121029",
    "Scheme establishement": "C121031",
    "Guideline availability": "C121032",
    "Shared material": "C121033",
    "Fatigue mitigation technique": "C121034",
    "Intercoder reliability metric": "C121036",
    "Conflict resolution": "C121037",
    "Approach type": "C121039",
    "Algorithm used": "C121040",
    "Running requirements": "C121041",
    "Documentation": "C121042",
    "Dependency": "C121043",
    "Release format": "C121046",
    "Evaluation metric": "C121048",
    "Validation procedure": "C121049",
    "Baseline comparsion type": "C121051",
}
